version: "3.7"
services:
  app:
    build:
      args:
        user: User
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: keepcoin
    container_name: keepcoin-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - keepcoin

  db:
    image: mysql:5.7
    container_name: keepcoin-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: keepcoin
      MYSQL_ROOT_PASSWORD: keepcoin
      MYSQL_PASSWORD: keepcoin
      MYSQL_USER: keepcoin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - keepcoin

  nginx:
    image: nginx:1.17-alpine
    container_name: keepcoin-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d
    networks:
      - keepcoin

networks:
  keepcoin:
    driver: bridge

volumes:
  db-data:
    external: true
